// const fs=require('fs');
// const quote="Rhagavi is beautiful";

// fs.writeFile('./awesome.html','quote',(err)=>
// {
//     console.log('completed writing');
// });
const fs=require("fs");
// const quote2="Live more worry less";
// console.log(process.argv);
// const[, , noofFiles]=process.argv;

// for(let i=1;i<=noofFiles;i++)
// {
//     fs.writeFile(`./backup/text-${i}.html`,quote2,(err)=>
// {
//     console.log("completed");
// });

// }

// fs.readFile(`./cool123.txt`,"utf-8",(err,data)=>
// {
//     if(err)
//     {
//         console.log("😒",err);
//     }
//     else{
//         console.log(data);
//     }
// })
// const quote3="Dream without fear";
// fs.writeFile(`./fun.html`,quote3,(err)=>
// {
//     console.log("complered writing!!!");
//     fs.appendFileSync(`./fun.html`,quote3,(err)=>
//     {
//         console.log("completed updating!!!");

//     }
// )});

